name: jsAction
description: calculates the sum of two numbers
inputs:
  number1:
    description: first number
    required: true
    default: 0
  number2:
    description: second number
    required: true
    default: 0
outputs:
  result:
    description: sum of the two numbers
runs:
  using: node20
  main: dist/index.js
